name: Deploy All Workers
on:
  push:
    branches:
      - main

jobs:
  deploy-mitv:
    runs-on: ubuntu-latest
    name: Deploy mitv
    steps:
      - uses: actions/checkout@v4
      - name: Deploy mitv
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy mitv/mitv.js --name 0417mitv

  deploy-chaozhou:
    runs-on: ubuntu-latest
    name: Deploy chaozhou
    steps:
      - uses: actions/checkout@v4
      - name: Deploy chaozhou
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy 潮汕/chaozhou.js --name 0417chaozhou

  deploy-zubo:
    runs-on: ubuntu-latest
    name: Deploy zubo
    steps:
      - uses: actions/checkout@v4
      - name: Deploy zubo
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy 组播/zubo.js --name 0414zubo

  deploy-gdty:
    runs-on: ubuntu-latest
    name: Deploy gdty
    steps:
      - uses: actions/checkout@v4
      - name: Deploy gdty
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy 广东/gdty.js --name 0415gdty

  deploy-worker:
    runs-on: ubuntu-latest
    name: Deploy worker
    steps:
      - uses: actions/checkout@v4
      - name: Deploy worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy worker.js --name 0413worker
